package meldbase

import "errors"

var (
	ErrClosed                            = errors.New("meldbase: database is closed")
	ErrInvalidDocument                   = errors.New("meldbase: invalid document")
	ErrInvalidFilter                     = errors.New("meldbase: invalid filter")
	ErrInvalidUpdate                     = errors.New("meldbase: invalid update")
	ErrMutationLimit                     = errors.New("meldbase: mutation affected-row limit exceeded")
	ErrWriteConflict                     = errors.New("meldbase: write transaction snapshot conflicted")
	ErrWriteTransactionUnsupported       = errors.New("meldbase: write transactions require a durable database")
	ErrNotFound                          = errors.New("meldbase: document not found")
	ErrDuplicateID                       = errors.New("meldbase: duplicate document id")
	ErrInvalidCollection                 = errors.New("meldbase: invalid collection")
	ErrImmutableID                       = errors.New("meldbase: _id is immutable")
	ErrSlowConsumer                      = errors.New("meldbase: change consumer is too slow")
	ErrCorrupt                           = errors.New("meldbase: corrupt database")
	ErrUnsupportedFormat                 = errors.New("meldbase: unsupported storage format or required feature")
	ErrDuplicateKey                      = errors.New("meldbase: duplicate index key")
	ErrInvalidIndex                      = errors.New("meldbase: invalid index")
	ErrCompoundIndexUnsupported          = errors.New("meldbase: compound or descending indexes are unsupported")
	ErrDurability                        = errors.New("meldbase: durability failure; writes are disabled")
	ErrInvalidDelta                      = errors.New("meldbase: invalid query delta")
	ErrHistoryLost                       = errors.New("meldbase: requested history is no longer retained")
	ErrDestinationExists                 = errors.New("meldbase: destination already exists")
	ErrCompactionUnsupported             = errors.New("meldbase: compaction requires an open durable database")
	ErrCompactionDestinationExists       = errors.New("meldbase: compaction destination already exists")
	ErrReclamationUnsupported            = errors.New("meldbase: page reclamation requires an open durable database")
	ErrInvalidReclamationOptions         = errors.New("meldbase: invalid reclamation options")
	ErrReclamationConflict               = errors.New("meldbase: online reclamation conflicted with concurrent writes")
	ErrBackupUnsupported                 = errors.New("meldbase: physical backup requires an open durable database")
	ErrBackupDestinationExists           = errors.New("meldbase: backup destination already exists or is the source")
	ErrVerificationUnsupported           = errors.New("meldbase: verification requires an existing database")
	ErrDatabaseLocked                    = errors.New("meldbase: database is locked by another process")
	ErrRollbackDetected                  = errors.New("meldbase: database rollback detected")
	ErrDatabaseIdentity                  = errors.New("meldbase: unexpected database identity")
	ErrInsecureFileMode                  = errors.New("meldbase: database file permissions are not owner-private")
	ErrRollbackAnchorRequired            = errors.New("meldbase: rollback anchor is missing; explicit initialization is required")
	ErrRollbackAnchor                    = errors.New("meldbase: rollback anchor durability failure")
	ErrInvalidRollbackProtection         = errors.New("meldbase: invalid rollback protection options")
	ErrRecoveryRequired                  = errors.New("meldbase: startup recovery required by the selected policy")
	ErrInvalidResourceLimits             = errors.New("meldbase: invalid resource limits")
	ErrResourceLimit                     = errors.New("meldbase: resource limit exceeded")
	ErrIndexBuildUnsupported             = errors.New("meldbase: resumable index builds require a durable database")
	ErrIndexBuildNotFound                = errors.New("meldbase: index build not found")
	ErrIndexBuildExists                  = errors.New("meldbase: index build already exists")
	ErrIndexBuildFailed                  = errors.New("meldbase: index build is in a terminal failed state")
	ErrInvalidIndexBuildSchedulerOptions = errors.New("meldbase: invalid index build scheduler options")
	ErrIndexBuildSchedulerRunning        = errors.New("meldbase: index build scheduler already running")
	ErrInvalidCommitCoordinatorOptions   = errors.New("meldbase: invalid V2 commit coordinator options")
	ErrInvalidReplayDeliveryTimeout      = errors.New("meldbase: invalid V2 replay delivery timeout")
	ErrDurableConsumerUnsupported        = errors.New("meldbase: durable change consumers require a durable database")
	ErrDurableConsumerExists             = errors.New("meldbase: durable change consumer already exists")
	ErrDurableConsumerNotFound           = errors.New("meldbase: durable change consumer not found")
	ErrReplicaReadOnly                   = errors.New("meldbase: follower is read-only")
	ErrReplicaSequence                   = errors.New("meldbase: follower change token is not the next sequence")
	ErrReplicaProtocol                   = errors.New("meldbase: invalid replication protocol frame")
	ErrReplicaSourceActive               = errors.New("meldbase: replication source consumer already has an active session")
	ErrReplicaPromotionAuthority         = errors.New("meldbase: follower promotion requires an external fencing authority")
	ErrReplicaPromotionFence             = errors.New("meldbase: follower promotion fence does not match local state")
	ErrReplicaPromotionWriteFence        = errors.New("meldbase: follower promotion requires a configured primary write fence")
	ErrReplicaPromoted                   = errors.New("meldbase: follower has been promoted and no longer accepts replication")
	ErrPrimaryWriteFence                 = errors.New("meldbase: primary write fence rejected the commit")
	// ErrCommitOutcomeUnknown means cancellation or a lost caller connection
	// raced an already-admitted durable write. Callers must reconcile by the
	// returned document ID(s), rather than retrying business logic blindly.
	ErrCommitOutcomeUnknown = errors.New("meldbase: commit outcome is unknown; do not retry blindly")
)
