// Command generate-root-api mirrors the internal database implementation
// through the module-root package during the pre-Beta import-path migration.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	implementationDirectory = "internal/database"
	outputFile              = "api_gen.go"
)

func main() {
	files, err := parser.ParseDir(token.NewFileSet(), implementationDirectory, func(info os.FileInfo) bool {
		return !strings.HasSuffix(info.Name(), "_test.go")
	}, parser.ParseComments)
	if err != nil {
		fatal(err)
	}
	packageFiles, ok := files["database"]
	if !ok {
		fatal(fmt.Errorf("missing package database in %s", implementationDirectory))
	}

	names := make([]string, 0, len(packageFiles.Files))
	for name := range packageFiles.Files {
		names = append(names, name)
	}
	sort.Strings(names)

	var output bytes.Buffer
	output.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	output.WriteString("package meldbase\n\n")
	output.WriteString("import (\n")
	output.WriteString("\t\"context\"\n")
	output.WriteString("\t\"io\"\n")
	output.WriteString("\t\"time\"\n\n")
	output.WriteString("\tdatabase \"github.com/crapthings/meldbase/internal/database\"\n")
	output.WriteString(")\n\n")
	for _, name := range names {
		file := packageFiles.Files[name]
		for _, declaration := range file.Decls {
			emitDeclaration(&output, declaration)
		}
	}

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		fatal(err)
	}
	if err := os.WriteFile(filepath.Clean(outputFile), formatted, 0o644); err != nil {
		fatal(err)
	}
}

func emitDeclaration(output *bytes.Buffer, declaration ast.Decl) {
	switch declaration := declaration.(type) {
	case *ast.FuncDecl:
		if declaration.Recv == nil && declaration.Name.IsExported() {
			emitDoc(output, declaration.Doc)
			emitFunction(output, declaration)
		}
	case *ast.GenDecl:
		for _, specification := range declaration.Specs {
			switch specification := specification.(type) {
			case *ast.TypeSpec:
				if specification.Name.IsExported() {
					emitDoc(output, declaration.Doc, specification.Doc)
					fmt.Fprintf(output, "type %s = database.%s\n\n", specification.Name.Name, specification.Name.Name)
				}
			case *ast.ValueSpec:
				for _, name := range specification.Names {
					if !name.IsExported() {
						continue
					}
					emitDoc(output, declaration.Doc, specification.Doc)
					if declaration.Tok == token.CONST {
						fmt.Fprintf(output, "const %s = database.%s\n\n", name.Name, name.Name)
					} else {
						fmt.Fprintf(output, "var %s = database.%s\n\n", name.Name, name.Name)
					}
				}
			}
		}
	}
}

func emitFunction(output *bytes.Buffer, declaration *ast.FuncDecl) {
	arguments := functionArguments(declaration.Type.Params)
	var signature bytes.Buffer
	if err := printer.Fprint(&signature, token.NewFileSet(), declaration.Type); err != nil {
		fatal(err)
	}
	printed := strings.TrimPrefix(signature.String(), "func")
	fmt.Fprintf(output, "func %s%s {\n", declaration.Name.Name, printed)
	call := fmt.Sprintf("database.%s(%s)", declaration.Name.Name, strings.Join(arguments, ", "))
	if declaration.Type.Results == nil || len(declaration.Type.Results.List) == 0 {
		fmt.Fprintf(output, "\t%s\n", call)
	} else {
		fmt.Fprintf(output, "\treturn %s\n", call)
	}
	output.WriteString("}\n\n")
}

func functionArguments(parameters *ast.FieldList) []string {
	if parameters == nil {
		return nil
	}
	arguments := make([]string, 0, len(parameters.List))
	unnamed := 0
	for _, field := range parameters.List {
		if len(field.Names) == 0 {
			field.Names = []*ast.Ident{ast.NewIdent(fmt.Sprintf("argument%d", unnamed))}
			unnamed++
		}
		for _, name := range field.Names {
			argument := name.Name
			if _, variadic := field.Type.(*ast.Ellipsis); variadic {
				argument += "..."
			}
			arguments = append(arguments, argument)
		}
	}
	return arguments
}

func emitDoc(output *bytes.Buffer, groups ...*ast.CommentGroup) {
	for _, group := range groups {
		if group == nil {
			continue
		}
		text := strings.TrimSpace(group.Text())
		if text == "" {
			continue
		}
		for _, line := range strings.Split(text, "\n") {
			fmt.Fprintf(output, "// %s\n", line)
		}
		return
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "generate root API:", err)
	os.Exit(1)
}
